### ISSUE TITLE
Consider `wrapPalt` option

### ISSUE THREAD

**Issue by yamatoiizuka** [yamatoiizuka/palt-typesetting#54]
current: 

```css
.p {
  font-feature-setting: palt;
  letter-spacing: 0.12em;
}

.typeset-latin {
  font-feature-setting: palt;
  letter-spacing: 0.05em;
}
```

with `wrapPalt` option:

```css
.p {
  letter-spacing: 0.05em;
}

.typeset-palt {
  font-feature-setting: palt;
  letter-spacing: 0.12em;
}
```
