### ISSUE TITLE
Unnecessary Spaces in Safari's Reader Mode

### ISSUE THREAD

**Issue by yamatoiizuka** [yamatoiizuka/palt-typesetting#93]
<img width="1143" alt="Screenshot 2024-02-25 at 13 58 44" src="https://github.com/yamatoiizuka/palt-typesetting/assets/47804982/9e060c94-f688-4463-88fd-a8c70ceef45b">
Safari のリーダーモードで、カーニングや四分アキスペースで使われているスペース／NBSP が出力されてしまう。

**Comment by yamatoiizuka** [comment]
```css
.typeset-thinspace, .typeset-kerning {
  visibillity: hidden;
}

```

では、リーダーモードに不要な半角スペースは出力されなくなったが、今度は `text-decoration` が効かなくなってしまう。（カーニングの適用がある「よ-う-な」間が空いてしまう。）
<img width="1117" alt="Screenshot 2024-02-25 at 14 04 22" src="https://github.com/yamatoiizuka/palt-typesetting/assets/47804982/b41b0cc1-c3be-43b2-bcf5-549447c25b68">

**Comment by yamatoiizuka** [comment]
HTML 側でスペースを出力するのをやめ、CSS の before/after 擬似要素の content で出力するのがよさそう。

例）
```css
.typeset-thin-space::after,
.typeset-kerning::after {
  font-family: ling-one;
  content: ' ';
}
```
