### ISSUE TITLE
Line End Wrap in iOS Safari 

### ISSUE THREAD

**Issue by yamatoiizuka** [yamatoiizuka/palt-typesetting#99]
<img src="https://github.com/yamatoiizuka/palt-typesetting/assets/47804982/1d8a1c5e-9170-483f-aa10-433ad0ea0124" width=400 />  

iOS Safari にて、特定時の条件下（組版のオンオフ切り替えを行なった場合）で行末禁則が崩れる事例が見られた。「て-、」間には負値のカーニングがかかっており、不要な after 擬似要素が原因と思われる。

**現状**
```css
.typeset-thin-space::after,
.typeset-kerning::after {
  content: attr(data-content); /* Space または No-Break Space */
  font-family: ling-one; /* カスタムフォントのスペースを使用します。 */
  line-height: 0; /* 空白による行の高さの影響を無視します。 */
}
```

**解決策**
`data-content` 属性を持つタグにのみ、content などのスタイルを当てるように変更する。

```css
.typeset-thin-space[data-content]::after,
.typeset-kerning[data-content]::after {
  content: attr(data-content); /* Space または No-Break Space */
  font-family: ling-one; /* カスタムフォントのスペースを使用します。 */
  line-height: 0; /* 空白による行の高さの影響を無視します。 */
}
```
